#!/usr/bin/python

# No important : The __file__ constant is useless in this case to get the current script's path, so we will use sys
# and os to find it.

import sys, os
prog_path = sys.argv[0]
# the command may be a link
try : pp = os.readlink(prog_path)
except OSError : pass  # it is not a link
else : prog_path = pp # it is a link
prefix = os.path.realpath('/'.join(prog_path.split('/')[0:-1])) # path to the current script
filename = "/avatar/avatar.blend" # name of the blender file to start
options = ["blenderplayer"] # parametres passes a blenderplayer
options.insert(1, "-g show_framerate = 1 show profile = 1") # debug infos
#options.insert(1, "-f") # fullscreen mode
options.insert(1, "-w 1280 800") # resolution of window or in fullscreen
options.append(prefix+filename) # set the blender file path to run
print(' '.join(options))
os.execvp("blenderplayer", options) # Execute the blender file and replace this process.
